### ISSUE TITLE
x86_64 architecture not supported

### ISSUE THREAD

**Issue by thomasfw** [ttatarinov/lineapro-phonegap-plugin#4]
Xcode throws up the following errors when I attempt to build and deploy on a 64bit device.

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DTDevices", referenced from:
      objc-class-ref in LineaProCDV.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

(Many thanks for the plugin)

**Comment by jerHutchings** [comment]
+1 Me too. Most of the standard fixes for this issue have failed. Any help would be appreciated.

**Comment by GauravButola** [comment]
I was also facing the same issue and finally figured it out. Here's how I fixed it:

Apparently, the SDK included along with the plugin is old and doesn't support arch64. So, I downloaded the latest Linea Pro SDK and replaced the `libdtdev.a` and `DTDevices.h` files with the ones in latest SDK.

You also need to add the required frameworks `AudioToolbox.framework` and `MediaPlayer.framework`, which can be automatically done if you add it to `plugin.xml`.

I've sent a pull request for this fix as well https://github.com/ttatarinov/lineapro-phonegap-plugin/pull/8

Hope this helps.

**Comment by warrenbell** [comment]
Gaurav,

Where can I see your plugin.xml file. I have also created a fork that has a newer SDK. It has been working fine, but I was not aware of the added frameworks. ttatarinov had asked for a pull request, but I just never got around to it.

**Comment by GauravButola** [comment]
Hi Warren,

You can see my plugin.xml here[1], and here's[2] the change I've sent in the PR.

[1] https://github.com/GauravButola/lineapro-phonegap-plugin/blob/master/plugin.xml#L34-L35
[2] https://github.com/GauravButola/lineapro-phonegap-plugin/commit/32d3dba4f042597a809fe79ed349928fcf98e778

**Comment by jameswagoner** [comment]
@GauravButola Where is the latest SDK located? Curious to know if there is anything in a newer version of the SDK that makes it work updating.
